name = "Quizify"
uuid = "ce4eee6e-572b-4073-8745-52c3a1f458e8"
authors = ["berrli <liam.j.berrisford@bath.edu>"]
version = "0.2.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1"
