# docs/Project.toml
name = "QuizifyDocs"
uuid = "4a6e3064-a223-46ac-a1bc-c4d5b849ac9b"    # just pick/generate a new one
version = "0.1.0"

[deps]
Quizify    = "ce4eee6e-572b-4073-8745-52c3a1f458e8"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1"
