name: "Docs"

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"

      - name: Install dependencies
        run: julia --project=docs -e 'import Pkg; Pkg.instantiate()'

      - name: Build docs
        run: julia --project=docs docs/make.jl

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          publish_branch: gh-pages
